export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const DAJ_MENU = 'DAJ_MENU';

export const WCZYTAJ_PORTFEL = 'WCZYTAJ_PORTFEL'
export const WCZYTAJ_LISTE_OBIEKTOW_PORTFELA  = 'WCZYTAJ_LISTE_OBIEKTOW_PORTFELA'
export const WCZYTAJ_LISTE_ELEMENTOW_PORTFELA = 'WCZYTAJ_LISTE_ELEMENTOW_PORTFELA'

export const BLAD_PORTFEL = 'BLAD_PORTFEL';
export const DAJ_PORTFEL = 'DAJ_PORTFEL';
export const USTAW_ZAZNACZONY_OBIEKT = 'USTAW_ZAZNACZONY_OBIEKT';
export const DAJ_LISTE_OBIEKTOW_PORTFELA = 'DAJ_LISTE_OBIEKTOW_PORTFELA';
export const DAJ_LISTE_ELEMENTOW_PORTFELA = 'DAJ_LISTE_ELEMENTOW_PORTFELA';

export const DODAJ_TAB = 'DODAJ_TAB';
export const ZAZNACZ_TAB = 'ZAZNACZ_TAB';